### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mikeseese** [Kubessandra/UE-Cropout-Multiplayer#1]
Hi, thanks for putting this project together! I just wanted to reach out and request what license do your modifications operate on? By omitting a license, it implies all rights reserved (at least in the US). Epic's IP will operate under the EULA, but your additional modifications can be separately licensed by you. Unfortunately your statement in the readme "Feel free to use the repo and report any bugs." isn't enough to let me do whatever I want legally.

You can find some examples of licenses at https://choosealicense.com. The MIT license might be what you're looking for if you want to let people use the project however they wish.

**Comment by Kubessandra** [comment]
Will add the MIT, yeah totally forgot about

**Comment by mikeseese** [comment]
Thanks!
